### ISSUE TITLE
Response Table freezes often and later after several refresh and changes in browser it loads. This issue causes loosing important booking at very necessary time.

### ISSUE THREAD

**Issue by dgowda6** [yashwanthm/cowin-vaccine-booking#16] opened 2021-05-13 08:06 UTC
![image](https://user-images.githubusercontent.com/9278211/118097310-25a49c80-b3f0-11eb-875f-bd1d861f660c.png)

**Comment by yashwanthm** [comment] 2021-05-13 12:38
![image](https://user-images.githubusercontent.com/1220402/118126568-22bca280-b416-11eb-953b-26ca41f4fe66.png)
Unable to reproduce. Closing.

**Closed by yashwanthm** 2021-05-13 12:38 UTC
