### ISSUE TITLE
Beneficiaries array required, with length 1-4

### ISSUE THREAD

**Issue by boseab** [yashwanthm/cowin-vaccine-booking#67] opened 2021-05-28 11:40 UTC
This is the error message coming what to do

**Comment by yashwanthm** [comment] 2021-05-28 12:35
Did you select beneficiaries?

**Comment by yashwanthm** [comment] 2021-05-28 18:05
Closing as the issue is likely with not selecting beneficiaries.

**Closed** 2021-05-28 18:04 UTC
