### ISSUE TITLE
Slots are not reflecting

### ISSUE THREAD

**Issue by smitra91** [yashwanthm/cowin-vaccine-booking#59] opened 2021-05-24 11:46 UTC
Even if we can see slots are available but the portal is not tracking and helping us to book.

**Comment by yashwanthm** [comment] 2021-05-24 12:30
Where are you seeing the slots available? @smitra91

**Comment by vijaykagarwal** [comment] 2021-05-24 13:10
Hi, much appreciate the code provided and I have tested it with random place 2 days back. Unfortunately am also facing this issue now. While am getting slots alert on telegram but the code keeps running and doesnt show any available slot.

**Comment by yashwanthm** [comment] 2021-05-24 14:08
I'm also seeing the disconnect with availability on some telegram bots vs the app. Any insights on how the telegram bots are able to detect the availability will be very helpful.
Optionally I've opened an API for telegram bots to integrate with our app here. Details available at https://github.com/yashwanthm/cowin-vaccine-booking#readme 

OTP issue will go away in 5 to 10 mins. @vijaykagarwa

**Comment by yashwanthm** [comment] 2021-05-24 17:08
Are these slots available on Cowin when you open it after notification? 
I think we need a comparision here between the telegram notifications, the app and cowin

**Comment by yashwanthm** [comment] 2021-05-25 02:49
It confirmed that the information on the API response is shown as is. I'm not sure how these telegram bots are able to get the availability info.
I'm trying a different endpoint for tracking availability. If anyone is interested, please try https://github.com/yashwanthm/cowin-vaccine-booking/tree/sessions and let me know if it works for you.

**Comment by yashwanthm** [comment] 2021-05-25 03:59
I've deployed a new version that uses a different type of tracking after some testing. Please try it out. @vijaykagarwal @smitra91 

The issue should be resolved now.

**Comment by vijaykagarwal** [comment] 2021-05-25 04:36
Thanks Yashant. Sorry am not able to respond since caught with the office
work. But will try this new app.

Thank you.

**Comment by yashwanthm** [comment] 2021-05-25 04:40
2021-05-25-10:09:32 - This build has option to change tracking mode. 
I'll need help with testing.

**Comment by vijaykagarwal** [comment] 2021-05-25 04:42
Happy to connect Yashwanth, but can i please connect late in the evening. I
would not be able to take out time at the moment

**Comment by NaveenKS** [comment] 2021-05-25 04:58
Hi @yashwanthm, I also observed the same problem reported above. I'll try to book and let you know. Thank you for the update.

**Comment by yashwanthm** [comment] 2021-05-25 06:15
I got my slot confirmed. It works. Closing this.

**Closed by yashwanthm** 2021-05-25 06:15 UTC
